### ISSUE TITLE
组合数学还有更多的笔记吗

### ISSUE THREAD

**Issue by AndSonder** [mobyw/MasterCourseNotes#1]
学长你好，请问组合数学还有更多的笔记嘛

**Comment by mobyw** [comment]
后续的没有用 LaTeX 来写，看作业题和例题复习就行了

**Comment by AndSonder** [comment]
学长整理的实在太好了，能不能看看学长的笔记呢 我的邮箱 changlu264@163.com，方便的话不知道能不能加个wx

**Comment by mobyw** [comment]
有整理的都已经在仓库了，其他的都是纸质或没有条理的，没有什么参考价值

**Comment by AndSonder** [comment]
好滴了解了，谢谢学长
